// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.3
// source: queda.proto

package convert

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuedaPayload struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MacAddr   string                 `protobuf:"bytes,1,opt,name=MacAddr,proto3" json:"MacAddr,omitempty"`
	Time      *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=Time,proto3" json:"Time,omitempty"`
	Intensity float32                `protobuf:"fixed32,3,opt,name=Intensity,proto3" json:"Intensity,omitempty"`
}

func (x *QuedaPayload) Reset() {
	*x = QuedaPayload{}
	mi := &file_queda_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuedaPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuedaPayload) ProtoMessage() {}

func (x *QuedaPayload) ProtoReflect() protoreflect.Message {
	mi := &file_queda_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuedaPayload.ProtoReflect.Descriptor instead.
func (*QuedaPayload) Descriptor() ([]byte, []int) {
	return file_queda_proto_rawDescGZIP(), []int{0}
}

func (x *QuedaPayload) GetMacAddr() string {
	if x != nil {
		return x.MacAddr
	}
	return ""
}

func (x *QuedaPayload) GetTime() *timestamppb.Timestamp {
	if x != nil {
		return x.Time
	}
	return nil
}

func (x *QuedaPayload) GetIntensity() float32 {
	if x != nil {
		return x.Intensity
	}
	return 0
}

var File_queda_proto protoreflect.FileDescriptor

var file_queda_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x71, 0x75, 0x65, 0x64, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x71,
	0x75, 0x65, 0x64, 0x61, 0x5f, 0x62, 0x75, 0x66, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x76, 0x0a, 0x0c, 0x51, 0x75, 0x65,
	0x64, 0x61, 0x50, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x4d, 0x61, 0x63,
	0x41, 0x64, 0x64, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4d, 0x61, 0x63, 0x41,
	0x64, 0x64, 0x72, 0x12, 0x2e, 0x0a, 0x04, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x04, 0x54,
	0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x49, 0x6e, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x74,
	0x79, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x63, 0x6f, 0x6e, 0x76, 0x65, 0x72, 0x74, 0x2f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_queda_proto_rawDescOnce sync.Once
	file_queda_proto_rawDescData = file_queda_proto_rawDesc
)

func file_queda_proto_rawDescGZIP() []byte {
	file_queda_proto_rawDescOnce.Do(func() {
		file_queda_proto_rawDescData = protoimpl.X.CompressGZIP(file_queda_proto_rawDescData)
	})
	return file_queda_proto_rawDescData
}

var file_queda_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_queda_proto_goTypes = []any{
	(*QuedaPayload)(nil),          // 0: queda_buf.QuedaPayload
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_queda_proto_depIdxs = []int32{
	1, // 0: queda_buf.QuedaPayload.Time:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_queda_proto_init() }
func file_queda_proto_init() {
	if File_queda_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_queda_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_queda_proto_goTypes,
		DependencyIndexes: file_queda_proto_depIdxs,
		MessageInfos:      file_queda_proto_msgTypes,
	}.Build()
	File_queda_proto = out.File
	file_queda_proto_rawDesc = nil
	file_queda_proto_goTypes = nil
	file_queda_proto_depIdxs = nil
}
